ALPHABET_UPPER = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
ALPHABET_LOWER = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];
PHRASES = [
  "I think it's wrong that only one company makes Monopoly.",
  "Every crowd has a silver lining.",
  "Never invest your money in anything that eats or needs repairing.",
  "Ask your child what he wants for dinner only if he's buying.",
  "What is a friend? A single soul dwelling in two bodies.",
  "If you're alone in the kitchen and you drop the lamb, just pick it up. Who's going to know?",
  "Life is short. Avoid causing yawns.",
  "I looked up my family tree and found out I was the sap.",
  "If your desk isn't covered, you probably aren't doing your job.",
  "Gray hair is God's graffiti.",
  "Happiness is good health and a bad memory.",
  "The trouble with being punctual is that nobody's there to appreciate it.",
  "Never go to bed mad. Stay up and fight.",
  "If you tickle the earth with a hoe, she laughs with a harvest.",
  "It's not the most intellectual job in the world, but I do have to know the letters.",
  "You can't expect to hit the jackpot if you don't put a few nickels in the machine.",
  "You know you're getting old when the candles cost more than the cake.",
  "You're not drunk if you can lie on the floor without holding on.",
  "Love letters are campaign promises of the heart.",
  "A severed foot is the best stocking stuffer.",
  "Wrinkles should merely indicate where smiles have been.",
  "No day is so bad it can't be fixed with a nap.",
  "Blessed are the young, for they shall inherit the national debt.",
  "Turn your wounds into wisdom.",
  "The road to success is always under construction.",
  "If God wanted us to bend over, he'd put diamonds on the floor.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "There is never enough time, unless you're serving it.",
  "You can't have everything. Where would you put it?",
  "The person who knows how to laugh at himself will never cease to be amused.",
  "You moon the wrong person at the office party and suddenly you're not professional anymore.",
  "All you need is love. But a little chocolate now and then doesn't hurt.",
  "Honesty will never break you.",
  "Don't knock the weather. If it didn't change once in a while, nine out of ten people couldn't start a cconversation.",
  "The only time a woman really succeeds in changing a man is when he is a baby.",
  "A computer once beat me at chess, but it was no match for me at kickboxing.",
  "Millions long for immortality who don't know what to do with themselves on a rainy Sunday afternoon.",
  "Husbands are like fires. They go out if unattended.",
  "One of the advantages of being disorderly is that one is always making exciting discoveries.",
  "Nobody can make you feel inferior without your permission.",
  "If a man smiles all the time, he's probably selling something that doesn't work.",
  "It's a small world, but I wouldn't want to paint it.",
  "The perfect lover is one who turns into a pizza at four A.M.",
  "I haven't spoken to my wife in years. I didn't want to interrupt her.",
  "Keep your face to the sunshine and you cannot see the shadow.",
  "Casual sex is the best because you don't have to wear a tie.",
  "If you want to kill any idea in the world, get a committee working on it.",
  "You'll always miss one hundred percent of the shots you don't take.",
  "Love your enemy. It will drive him nuts.",
  "If you always do waht interests you, at least one person is pleased.",
  "Whether you think you can do a thing or not, you're right.",
  "Gorgeous hair is the best revenge.",
  "Never go to a doctor whose houseplants have died.",
  "Laughter is the closest distance between two people.",
  "Classic: a book which people praise and don't read.",
  "There are no ordinary cats.",
  "Disney has the best casting. If he doesn't like an actor, he simply tears him up.",
  "If you die in an elevator, be sure to press the UP button.",
  "A smile is a curve that sets everything straight.",
  "Giving birth is like taking your lower lip and forcing it over your head.",
  "Never trust a computer you can't throw out the window.",
  "Hold a true friend with both your hands.",
  "Taking pleasure in life is a woman's best cosmetic.",
  "I think we developed language because of our deep inner need to complain.",
  "Never judge a book by its movie.",
  "God not only plays dice, he throws them in the corner where you can't see them.",
  "Never interrupt your enemy while he is making a mistake.",
  "You can't blame gravity for falling in love.",
  "Without music, life is ajourney through a desert.",
  "Everywhere is walking distance if you have the time.",
  "Whoever named it necking was a poor judge of anatomy.",
  "I was a vegetarian until I started leaning toward the sunlight.",
  "",
];
